### ISSUE TITLE
explicit cut = NULL in makeOxygen triggers an error

### ISSUE THREAD

**Issue by grishin1** [metrumresearchgroup/sinew#8]
``` r
sinew::makeOxygen(lm, cut = NULL)
#> Warning in rep(yes, length.out = length(ans)): 'x' is NULL so the result
#> will be NULL
#> Error in ans[test & ok] <- rep(yes, length.out = length(ans))[test & ok]: replacement has length zero
```
`makeImport("somefile.R", cut = NULL)` does not trigger this error.

Does `makeImport` actually need NULL as default? It looks like its behaviour can be fully controlled by a **numerical** default value. So, why not cut = 0?

**Comment by yonicd** [comment]
Thank you for bringing up the issue. 

cut=NULL outputs a full list of all the functions to import from a namespace. since you dont know that upfront its a problem to just put a large number. 

the problem is that the null is not being passed through to the [cutOFF](https://github.com/metrumresearchgroup/sinew/blob/master/R/makeOxygen.R#L116) being passed into the makeSeeAlso.

**Comment by yonicd** [comment]
[fixed](https://github.com/metrumresearchgroup/sinew/commit/4a2039a5bc6b61cbe97ad90db8038ab12db3668e)
